---
#Author: Edgardo Cabral
#Fecha: 29/09/2022
#Objetivo: Playbook Ansible para instalacion de Docker-Engine, CORE. // Tutorial realizadopara Ubuntu Server.
#Version: 1.0
- hosts: all 
  become: true
  tasks:
    #Preparar Servidor para descargar e instalar Docker.
    - name: Actualizar apt
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes

    - name: Instala curl
      ansible.builtin.apt:
        name: curl
        state: present    
    
    - name: Permitir repositorios sobre HTTPS.
      ansible.builtin.shell: apt-get install ca-certificates curl gnupg lsb-release

    - name: Crear carpeta para llaves de docker
      ansible.builtin.file:
        path: /etc/apt/
        state: directory

    - name: Crear carpeta para llaves de docker 2
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory

    - name: Copiar llaver de docker al repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
      
    - name:  Configura repositorios
      ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      register: command_output

    - debug:
            var: command_output.stdout_lines

    # Instalando Docker Engine
    - name: Actualizar repos
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes

    - name: instalar docker engine, agrupado
      ansible.builtin.apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    #Iniciar Docker Engine
    - name: Iniciamos servicio docker
      ansible.builtin.shell: service docker start

    #Probamos Docker con docker con un hola mundo
    - name: Descargar y corre hola mundo.
      ansible.builtin.shell: docker run hello-world
      register: command_output

    - debug:
             var: command_output.stdout_lines
