#Author: Edgardo Cabral
#Fecha: 18/11/2022
#Objetivo: Playbook para instalar Docker Compose , solo sobre linux/ubuntu.
#Version: 1.0
- hosts: all 
  become: true
  tasks:
    #Actualizar repositorios
    - name: Actualizar apt
      ansible.builtin.apt:
        update: yes
        update_cache: yes
    
    - name: instalar Compose plugin
      ansible.builtin.apt:
        pkg: 
         - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: test compose 
      ansible.builtin.shell: docker compose Version
      register: command_output

    - debug: 
             var: command_output.stdout_lines

         