---

- name: update & upgrade linux
  gather_facts: false
  hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Actualizar apt
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
