---

- name: update & upgrade linux
  gather_facts: false
  hosts: all
  remote_user: root
  tasks:

    - name: Actualizar apt
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        